# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0816fa1f315254df9490691573d93d27ddce817b5aecf98cfb5007d8ea5bc540a333f6706fe0fe83d7734b241bdd5b3e66f411f027faab8cac9126edaa6d2f7

test:
  secret_key_base: 92c2191ba78e863ff7c5d0269a73ad21acbcd783bd0e1b6d514813aff7108f9ecfffec1551ca45d159970d004ac0687ef45e961c08e21200f4a0e92e95de7f45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
